FROM docker.io/library/ubuntu:18.04 as ubuntu18

RUN groupadd --gid 100999 mongodb; \
	useradd --uid 100999 --gid mongodb --home-dir /var/lib/mongodb mongodb; \
	mkdir -p /var/lib/mongodb; \
	chown -R mongodb:mongodb /var/lib/mongodb
RUN apt-get update && apt-get install -y libcurl4 && rm -rf /var/lib/apt/lists/*
